apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - auth/deployment.yaml
  - auth/service.yaml
  # - db/statefulset.yaml
  # - db/service.yaml
  # - db/configmap.yaml
  # - db/secret.yaml