apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../base
  - namespace.yaml


patches:
  - path: patch-deployment.yaml
    target:
      kind: Deployment

  # - path: db/patch-db.yaml
  #   target:
  #     kind: Deployment

images:
  - name: app/tc-auth-service
    newName: 147671223315.dkr.ecr.us-east-1.amazonaws.com/app/tc-auth-service
    # newName: <<account-id>>.dkr.ecr.us-east-1.amazonaws.com/app/web
    newTag: latest
