apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: production

resources:
  - ../base
  - namespace.yaml

patchesStrategicMerge:
  - auth/patch-deployment.yaml
  # - db/patch-db.yaml

images:
  - name: app/tc-auth-service
    newName: 123456789.dkr.ecr.us-east-1.amazonaws.com/app/tc-auth-service
    newTag: latest
