apiVersion: apps/v1
kind: Deployment
metadata:
  name: auth-service
spec:
  replicas: 3
  template:
    spec:
      containers:
        - name: tc-auth-service
          image: app/tc-auth-service:latest
          env:
            - name: ENVIRONMENT
              value: "production"
